plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.dagger.hilt)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "fox.foxiru.foxcat.fox2d"
    compileSdk = 37
    ndkVersion = "30.0.16138531"

    val nativeLibName = "fox2d"

    defaultConfig {
        applicationId = "fox.foxiru.foxcat.fox2d"
        minSdk = 23
        targetSdk = 37
        versionCode = 10
        versionName = "0.5v-alpha"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField("String", "NATIVE_LIB_NAME", "\"$nativeLibName\"")

        externalNativeBuild {
            cmake {
                cppFlags += listOf("-std=c++23", "-fno-exceptions", "-fno-rtti")
                arguments += listOf(
                    "-DANDROID_STL=c++_shared",
                    "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
                    "-DLIB_NAME=$nativeLibName",
                    "-GNinja",
                )
                ndk {
                    abiFilters += listOf("arm64-v8a", "armeabi-v7a")
                }
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.31.0+"
        }
    }

    buildFeatures {
        compose = true
        prefab = true
        buildConfig = true
    }

    //sourceSets["main"].jniLibs.srcDir("src/main/cpp/ExternalLibraries/ffmpeg/lib")
    packaging {
        //jniLibs { useLegacyPackaging = false }
        resources {
            excludes += setOf(
                "META-INF/LICENSE.md",
                "META-INF/LICENSE-notice.md",
                "META-INF/NOTICE.md",
                "META-INF/NOTICE",
                "META-INF/LICENSE",
            )
        }
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    
    kotlin {
        compilerOptions {
            jvmTarget.set(
                org.jetbrains.kotlin.gradle.dsl.JvmTarget
                    .fromTarget("21"),
            )
        }
    }
    
    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    
}

abstract class AutoTouchCxxBuildTask : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val cmakeListFiles: ConfigurableFileCollection

    @get:Internal
    abstract val lastModifiedCache: RegularFileProperty

    @get:Internal
    abstract val cxxDirs: ListProperty<File>

    @TaskAction
    fun run() {
        val cacheFile = lastModifiedCache.get().asFile
        val lastModified = if (cacheFile.exists()) {
            cacheFile.readText().toLongOrNull() ?: 0L
        } else 0L

        val newest = cmakeListFiles.files.maxOfOrNull { it.lastModified() } ?: 0L

        if (newest > lastModified) {
            logger.lifecycle("CMakeLists.txt changed! Touching CXX directories...")
            cxxDirs.get().forEach { dir ->
                if (dir.exists()) {
                    val process = ProcessBuilder(
                        "find", dir.absolutePath, "-exec", "touch", "{}", "+"
                    ).inheritIO().start()
                    val exitCode = process.waitFor()
                    if (exitCode == 0) {
                        logger.lifecycle("Touched all files in: ${dir.path}")
                    } else {
                        logger.warn("Warning: touch failed for ${dir.path} (exit $exitCode)")
                    }
                } else {
                    logger.lifecycle("Skipped (does not exist): ${dir.path}")
                }
            }
        } else {
            logger.lifecycle("CMakeLists.txt unchanged, skipping touch.")
        }

        cacheFile.parentFile.mkdirs()
        cacheFile.writeText(newest.toString())
    }
}

tasks.register<AutoTouchCxxBuildTask>("autoTouchCxxBuild") {
    group = "build setup"
    description = "Updates timestamps of all files in CXX directories if CMakeLists.txt changed."
    cmakeListFiles.setFrom(
        layout.projectDirectory.dir("src/main/cpp").asFileTree.matching {
            include("**/CMakeLists.txt")
        }
    )
    lastModifiedCache.set(layout.buildDirectory.file("lastCMakeModified.txt"))
    cxxDirs.set(
        listOf(
            layout.buildDirectory.dir(".cxx/Debug").get().asFile,
            layout.buildDirectory.dir(".cxx/Release").get().asFile,
            layout.projectDirectory.dir(".cxx/Debug").asFile,
            layout.projectDirectory.dir(".cxx/Release").asFile,
            layout.projectDirectory.dir(".cxx/RelWithDebInfo").asFile
        )
    )
}

tasks.matching {
    it.name.startsWith("configureCMake", ignoreCase = true) ||
    it.name.startsWith("generate", ignoreCase = true)
}.configureEach {
    dependsOn("autoTouchCxxBuild")
}

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs.nio)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.material.icons.core)
    implementation(libs.androidx.material.icons.extended)
    implementation(libs.androidx.constraintlayout.compose)
    implementation(libs.androidx.hilt.navigation.compose)
    implementation(libs.haze)
    implementation(libs.haze.blur)
    implementation(libs.okhttp)
    implementation(libs.okhttp.mockwebserver)
    implementation(libs.okio)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.atomicfu)
    implementation(libs.bouncycastle.bcprov)
    implementation(libs.bouncycastle.bcpkix)
    implementation(libs.reorderable)
    implementation(libs.dagger.hilt.android)
    ksp(libs.dagger.hilt.compiler)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}